---
abstract: "show your distribution's dependencies"
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Joseki-Command-depends
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Cwd: 0
  Dist::Joseki: 0
  File::Find: 0
  File::Slurp: 0
  Module::CoreList: 0
  Module::ExtractUse: 0
  Parse::CPAN::Packages: 0
  Perl::Version: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Joseki-Command-depends
  homepage: http://search.cpan.org/dist/Dist-Joseki-Command-depends/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/dist-joseki-command-depends.git
version: 0.01
